apiVersion: v2
name: fridge2fork
description: Fridge2Fork Application Helm Chart
type: application
version: 0.1.0
appVersion: "1.16.0"

# Dependencies
dependencies:
  - name: server
    version: "0.1.0"
    repository: "file://./charts/server"
    condition: server.enabled
  - name: database
    version: "16.7.14"
    repository: "file://./charts/database"
    condition: database.enabled
