# =================================================================
#  Loki SingleBinary 모드용 values.yaml
# =================================================================

# 1. 배포 모드 및 스토리지 타입 지정
deploymentMode: SingleBinary

loki:
  auth_enabled: false
  storage:
    type: filesystem

  commonConfig:
    replication_factor: 1

  limits_config:
    # Fluent Bit가 보내는 structured metadata 전송을 금지합니다
    allow_structured_metadata: false

  schemaConfig:
    configs:
      - from: "2024-04-01" # 이 설정이 적용될 시작 날짜
        store: tsdb # 최신 고성능 인덱스 저장 방식
        object_store: filesystem # 인덱스도 PVC(파일시스템)에 저장
        schema: v13 # 최신 스키마 버전
        index:
          prefix: index_ # 인덱스 파일의 접두사
          period: 24h # 인덱스 파일 생성 주기

# 2. SingleBinary 컴포넌트 설정
singleBinary:
  replicas: 1
  persistence:
    enabled: true
    size: 5Gi # 원하는 총 용량
    storageClassName: "openebs-hostpath"

# 3. 데이터 보존 기간 설정
tableManager:
  retention_deletes_enabled: true
  retention_period: 30d

# 4. 불필요한 다른 모드 컴포넌트 비활성화
# SimpleScalable 모드 컴포넌트
write:
  replicas: 0
read:
  replicas: 0
backend:
  replicas: 0

# Distributed(Microservices) 모드 컴포넌트
ingester:
  replicas: 0
distributor:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
indexGateway:
  replicas: 0
compactor:
  replicas: 0
# (기타 bloom, patternIngester 등도 모두 replicas: 0)

# 5. 불필요한 부가 기능 비활성화
gateway:
  enabled: false

minio:
  enabled: false

# 캐싱 비활성화
resultsCache:
  enabled: false
chunksCache:
  enabled: false

# 테스트용 canary 비활성화
lokiCanary:
  enabled: false

test:
  enabled: false
