loki:
  storage:
    type: filesystem

deploymentMode: SingleBinary

singleBinary:
  replicas: 1
  autoscaling:
    enabled: false
  persistence:
    enabled: true
    size: 100Gi
    storageClassName: "openebs-hostpath" # 실제 사용할 값으로 변경

tableManager:
  retention_deletes_enabled: true
  retention_period: 30d
