_internal_defaults_do_not_set:
  name: istio-ingressgateway
  labels:
    istio: ingressgateway
  service:
    type: LoadBalancer
    ports:
      - name: status-port
        port: 15021
        targetPort: 15021

      # [외부용] HTTP 접속 (30080 포트)
      # 외부에서 http://...:30080 으로 접속 시
      - name: http-custom
        port: 30080
        targetPort: 8080 # 파드(Envoy)의 HTTP 포트

      # [외부용] HTTPS 접속 (31443 포트)
      # 외부에서 https://...:31443 으로 접속 시
      - name: https-custom
        port: 31443
        targetPort: 8443 # 파드(Envoy)의 HTTPS 포트

      # [내부용] HTTP 표준 접속 (80 포트)
      # 내부에서 http://... 로 접속 시
      - name: http-standard
        port: 80
        targetPort: 8080 # 파드(Envoy)의 HTTP 포트

      # [내부용] HTTPS 표준 접속 (443 포트)
      # 내부에서 https://... 로 접속 시
      - name: https-standard
        port: 443
        targetPort: 8443 # 파드(Envoy)의 HTTPS 포트
  env:
    # Pilot(istiod)로부터 읽어올 Gateway/VS 네임스페이스를 콤마로 구분
    PILOT_SCOPE_GATEWAY_CONFIG: "*"
