localpv-provisioner:
  rbac:
    create: true

  # ✅ default StorageClass 설정
  defaultStorageConfig:
    enabled: true
    name: openebs-hostpath

engines:
  local:
    lvm:
      enabled: true
    zfs:
      enabled: false
  replicated:
    mayastor:
      enabled: false
      
loki:
  enabled: false

alloy:
  enabled: false
