engines:
  local:
    lvm:
      enabled: true
    zfs:
      enabled: false
  replicated:
    mayastor:
      enabled: false
      
loki:
  enabled: false

alloy:
  enabled: false

storageClass:
  name: openebs-hostpath
  isDefaultClass: true
  allowVolumeExpansion: true
  volumeBindingMode: WaitForFirstConsumer
  reclaimPolicy: Delete
  provisioner: openebs.io/local
