{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "bot.fullname" . }}
  labels:
    {{- include "bot.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.clusterSecretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.externalSecret.targetSecretName }}
    creationPolicy: Owner
  data:
    - secretKey: LOSTARK_API_KEY
      remoteRef:
        key: {{ .Values.externalSecret.gcpSecretName }}
{{- end }}
