# Default values for yangobot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
revisionHistoryLimit: 2

image:
  repository: ggorockee/yangobot
  pullPolicy: Always
  tag: "20260413-ab9e09d"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

secret:
  name: yangobot-credentials
  lostarkApiKeyRef: LOSTARK_API_KEY

extraEnv: []

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false

resources:
  requests:
    cpu: 20m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
  master:
    revisionHistoryLimit: 1
    persistence:
      enabled: false
    resources:
      requests:
        cpu: 20m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
