{{- if .Values.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kakao-client-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcpsm-secret-store
    kind: ClusterSecretStore
  target:
    name: {{ .Values.credentialSecret.name }}
    creationPolicy: Owner
  data:
    - secretKey: KAKAO_EMAIL
      remoteRef:
        key: prod-yangobot-credentials
        property: kakao_email
    - secretKey: KAKAO_PASSWORD
      remoteRef:
        key: prod-yangobot-credentials
        property: kakao_password
    - secretKey: ADMIN_USER_IDS
      remoteRef:
        key: prod-yangobot-credentials
        property: admin_user_ids
{{- end }}
