apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "yangobot.fullname" . }}-credentials
  labels:
    {{- include "yangobot.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcpsm-secret-store
    kind: ClusterSecretStore
  target:
    name: yangobot-credentials
    creationPolicy: Owner
  data:
    - secretKey: LOSTARK_API_KEY
      remoteRef:
        key: prod-yangobot-credentials
        property: LOSTARK_API_KEY
