{{- if .Values.virtualService.enabled }}
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ include "yangobot.fullname" . }}
  labels:
    {{- include "yangobot.labels" . | nindent 4 }}
spec:
  hosts:
    - {{ .Values.virtualService.host | quote }}
  gateways:
    - {{ .Values.virtualService.gateway }}
  http:
    - match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: {{ include "yangobot.fullname" . }}
            port:
              number: {{ .Values.service.port }}
{{- end }}
