backend:
  image:
    repository: ggorockee/py-airbnb-backend
    tag: "20250629-d790665"
  existingSecret: django-secrets
  service:
    port: 8000

  ingress:
    enabled: true
    className: "istio"
    annotations: {}
    hosts:
      - airbnb-beta.ggorockee.com
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  gateway:
    # Gateway가 트래픽을 받을 포트 설정
    port:
      number: 30080
      name: http
      protocol: HTTP

    # Ingress Gateway Pod를 선택하기 위한 셀렉터
    # 기본값은 Istio 설치 시 기본적으로 사용되는 레이블입니다.
    selector:
      istio: ingressgateway

    tls:
      httpsRedirect: false

  # Istio VirtualService 리소스에 대한 상세 설정
  virtualservice:
    # CORS 정책 설정
    corsPolicy:
      allowOrigins:
        - regex: "https?://.*"
      allowMethods:
        - "GET"
        - "POST"
        - "PUT"
        - "DELETE"
        - "OPTIONS"
        - "PATCH"
      allowHeaders:
        - "*"
      exposeHeaders:
        - "*"
      allowCredentials: true

frontend:
  image:
    repository: nginx
    tag: "1.29.0"

postgresql:
  global:
    postgresql:
      auth:
        username: ggorockee
        database: airbnb-dev
        existingSecret: airbnb-db-credentials
