backend:
  image:
    repository: ggorockee/py-airbnb-backend
    tag: "20250629-1ab0a97"
  existingSecret: django-secrets

  livenessProbe:
    enabled: true
    path: /healthz/ready # 1번 단계에서 추가한 헬스 체크 경로
    initialDelaySeconds: 30 # 파드가 시작되고 30초 후부터 검사 시작
    periodSeconds: 15     # 15초마다 검사
    timeoutSeconds: 5       # 응답 대기 시간 5초
    failureThreshold: 3     # 3번 연속 실패하면 재시작

  readinessProbe:
    enabled: true
    path: /healthz/ready # livenessProbe와 동일한 경로 사용 가능
    initialDelaySeconds: 10 # liveness보다 먼저, 더 짧게 검사 시작
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 2     # 2번 연속 실패 시 트래픽 차단
  
  service:
    port: 8000

  ingress:
    enabled: true
    className: "istio"
    annotations: {}
    hosts:
      - airbnb-beta-api.ggorockee.com
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  gateway:
    # Gateway가 트래픽을 받을 포트 설정
    port:
      number: 30080
      name: http
      protocol: HTTP

    # Ingress Gateway Pod를 선택하기 위한 셀렉터
    # 기본값은 Istio 설치 시 기본적으로 사용되는 레이블입니다.
    selector:
      istio: ingressgateway

    tls:
      httpsRedirect: false

  # Istio VirtualService 리소스에 대한 상세 설정
  virtualservice: {}
    # # CORS 정책 설정
    # corsPolicy:
    #   allowOrigins:
    #     - regex: "https?://.*"
    #   allowMethods:
    #     - "GET"
    #     - "POST"
    #     - "PUT"
    #     - "DELETE"
    #     - "OPTIONS"
    #     - "PATCH"
    #   allowHeaders:
    #     - "*"
    #   exposeHeaders:
    #     - "*"
    #   allowCredentials: true

frontend:
  image:
    repository: ggorockee/react-airbnb-frontend
    tag: "20250629-574bfe9"

  livenessProbe:
    enabled: true
    path: / # 1번 단계에서 추가한 헬스 체크 경로
    initialDelaySeconds: 30 # 파드가 시작되고 30초 후부터 검사 시작
    periodSeconds: 15     # 15초마다 검사
    timeoutSeconds: 5       # 응답 대기 시간 5초
    failureThreshold: 3     # 3번 연속 실패하면 재시작

  readinessProbe:
    enabled: true
    path: / # livenessProbe와 동일한 경로 사용 가능
    initialDelaySeconds: 10 # liveness보다 먼저, 더 짧게 검사 시작
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 2     # 2번 연속 실패 시 트래픽 차단
  
  service:
    port: 80

  ingress:
    enabled: true
    className: "istio"
    annotations: {}
    hosts:
      - airbnb-beta.ggorockee.com
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  gateway:
    # Gateway가 트래픽을 받을 포트 설정
    port:
      number: 30080
      name: http
      protocol: HTTP

    # Ingress Gateway Pod를 선택하기 위한 셀렉터
    # 기본값은 Istio 설치 시 기본적으로 사용되는 레이블입니다.
    selector:
      istio: ingressgateway

    tls:
      httpsRedirect: false

  # Istio VirtualService 리소스에 대한 상세 설정
  # virtualservice: {}
    # CORS 정책 설정
    # corsPolicy:
    #   allowOrigins:
    #     - regex: "https?://.*"
    #   allowMethods:
    #     - "GET"
    #     - "POST"
    #     - "PUT"
    #     - "DELETE"
    #     - "OPTIONS"
    #     - "PATCH"
    #   allowHeaders:
    #     - "*"
    #   exposeHeaders:
    #     - "*"
    #   allowCredentials: true

postgresql:
  global:
    postgresql:
      auth:
        username: ggorockee
        database: airbnb-dev
        existingSecret: airbnb-db-credentials
