backend:
  image:
    repository: ggorockee/py-airbnb-backend
    tag: "20250629-d790665"
  existingSecret: django-secrets

frontend:
  image:
    repository: nginx
    tag: "1.29.0"

postgresql:
  global:
    postgresql:
      auth:
        username: ggorockee
        database: airbnb-dev
        existingSecret: airbnb-db-credentials
