# redis subchart 기본값
replicaCount: 1

image:
  repository: redis
  tag: "7.2-alpine"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 6379

persistence:
  enabled: true
  storageClass: ""
  size: 1Gi
  accessMode: ReadWriteOnce

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}
