clusterName: "elasticsearch"
nodeGroup: "master"

replicas: 1
minimumMasterNodes: 1

roles:
  - master
  - data
  - ingest

esConfig:
  elasticsearch.yml: |
    network.host: 0.0.0.0
    discovery.type: single-node

# ─────────── 스토리지 (단일 노드라도 persistence ON) ───────────
volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 30Gi

# extraInitContainers:
#   - name: fix-permissions
#     image: busybox
#     command: ['sh', '-c', 'chown -R 1000:1000 /usr/share/elasticsearch/data']
#     volumeMounts:
#       - name: elasticsearch-master
#         mountPath: /usr/share/elasticsearch/data
      
resources:
  requests:
    cpu: "1000m"
    memory: "4Gi"
  limits:
    cpu: "1000m"
    memory: "4Gi"

readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 20
  periodSeconds: 10
  successThreshold: 3
  timeoutSeconds: 5
  
clusterHealthCheckParams: "wait_for_status=yellow&timeout=10s"
