replicas: 1
minimumMasterNodes: 1

resources:
  requests:
    cpu: "1Gi"
    memory: "512m"
  limits:
    cpu: "2Gi"
    memory: "1Gi"

volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 30Gi

readinessProbe:
  failureThreshold: 10
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 5

clusterHealthCheckParams: "wait_for_status=yellow&timeout=5s"
