clusterName: "elasticsearch"
nodeGroup: "master"

replicas: 1
minimumMasterNodes: 1

roles:
  - master
  - data
  - ingest

# esConfig:
#   elasticsearch.yml: |
#     network.host: 0.0.0.0
#     discovery.type: single-node

# ─────────── 스토리지 (단일 노드라도 persistence ON) ───────────
volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 30Gi


readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 20
  periodSeconds: 10
  successThreshold: 3
  timeoutSeconds: 5
  
clusterHealthCheckParams: "wait_for_status=yellow&timeout=10s"
