security:
  enabled: false
  tls:
    restEncryption: false

master:
  masterOnly: false
  replicaCount: 1
  # resources:
  #   limits:
  #     cpu: 1000m
  #     memory: 2Gi
  persistence:
    enabled: true
    size: 30Gi
    storageClass: openebs-hostpath

data:
  replicaCount: 0
  # resources:
  #   limits:
  #     cpu: 1000m
  #     memory: 2Gi
  # persistence:
  #   enabled: false
  #   size: 30Gi
  #   storageClass: openebs-hostpath
      
coordinating:
  replicaCount: 0
  # resources:
  #   limits:
  #     cpu: 1000m
  #     memory: 2Gi

ingest:
  replicaCount: 0
  # resources:
  #   limits:
  #     cpu: 1000m
  #     memory: 2Gi
