security:
  enabled: false
  tls:
    restEncryption: false

master:
  replicaCount: 1
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi

data:
  replicaCount: 1
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
      
coordinating:
  replicaCount: 1
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi

ingest:
  replicaCount: 1
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
