# Scrape Service Configuration
enabled: false  # 기본적으로 비활성화, parent values에서 override

replicaCount: 1

image:
  repository: ggorockee/fridge2fork-dev-server
  tag: sha-b13755d7
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000
  portName: "fastapi"

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "200m"

# ServiceAccount configuration
serviceAccount:
  create: true
  annotations: {}
  name: ""
  automount: true

# Pod security context
podSecurityContext:
  fsGroup: 2000

# Container security context
securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

# Pod annotations
podAnnotations: {}

# Image pull secrets
imagePullSecrets: []

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}

# Autoscaling
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Health check configuration
healthCheck:
  enabled: true
  livenessProbe:
    httpGet:
      path: /fridge2fork/v1/system/health
      port: http
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /fridge2fork/v1/system/health
      port: http
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3

# Secret configuration
# This secret must exist before deploying
secret:
  enabled: false  # 기본적으로 비활성화, parent values에서 override
  secretName: "fridge2fork-db-credentials"

# ConfigMap configuration
configMap:
  enabled: false  # 기본적으로 비활성화, parent values에서 override
  config: {}

# Init container for Alembic migration
initContainer:
  enabled: true  # Alembic migration을 위한 init container
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "100m"
