# Scrape Service Configuration
image:
  repository: ggorockee/fridge2fork-scrape
  tag: sha-8992dffe
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "200m"

# Job configuration
activeDeadlineSeconds: 7200  # 2시간 타임아웃
backoffLimit: 3  # 최대 재시도 횟수
restartPolicy: OnFailure
ttlSecondsAfterFinished: 2592000  # 한 달 (30일 * 24시간 * 60분 * 60초)
jobDisabled: true  # scrape job 비활성화

# ServiceAccount configuration
serviceAccount:
  create: true
  annotations: {}
  name: ""

# Pod security context
podSecurityContext:
  fsGroup: 2000

# Container security context
securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

# Pod annotations
podAnnotations: {}

# Image pull secrets
imagePullSecrets: []

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}

# Autoscaling
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

# Health check configuration (disabled by default)
healthCheck:
  enabled: false
  livenessProbe:
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /ready
      port: http
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3

# Environment variables from secrets
# REQUIRED: This secret must exist before deploying the chart
# The secret should contain database connection information
envFrom:
  - secretRef:
      name: fridge2fork-db-credentials  # Must exist in the namespace

# ConfigMap configuration
configMap:
  enabled: true
  config:
    # 크롤링 설정 (25만개 수집용)
    TARGET_RECIPE_COUNT: "250000"
    CONCURRENT_REQUESTS: "5"
    BATCH_SIZE: "100"
    REQUEST_DELAY: "1"
    BATCH_DELAY: "5"
    
    # 로깅 설정
    LOG_LEVEL: "INFO"
    
    # 모니터링 설정
    PROGRESS_INTERVAL: "1000"
    MEMORY_CHECK_INTERVAL: "10000"
    
    # 메모리 최적화 설정
    CHUNK_SIZE: "1000"
    CHUNK_DELAY: "30"

# Migration Job Configuration
migration:
  enabled: true  # migration job 활성화
  restartPolicy: OnFailure
  activeDeadlineSeconds: 21600  # 6시간 타임아웃
  backoffLimit: 3  # 최대 재시도 횟수
  ttlSecondsAfterFinished: 86400  # 1일 후 자동 삭제
  
  # 마이그레이션 리소스
  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "2Gi"
      cpu: "500m"
  
  # 마이그레이션 설정
  chunkSize: 500
  maxRecords: null
  
  config:
    LOG_LEVEL: "INFO"
    CHUNK_SIZE: "500"
    CHUNK_DELAY: "5"
  
  # 볼륨 설정 (기본적으로 비어있음)
  volumes: []
  volumeMounts: []
