certmanager:
  certi:
    - name: ggorockee-org-cert
      namespace: istio-system
      extraLabels: {}
      annotations: {}
      secretName: ggorockee-org-cert
      clusterIssuer:
        name: letsencrypt-cloudflare
      dnsNames:
        - "*.ggorockee.org"
        - "ggorockee.org"
    - name: ggorockee-com-cert
      namespace: istio-system
      extraLabels: {}
      annotations: {}
      secretName: ggorockee-com-cert
      clusterIssuer:
        name: letsencrypt-cloudflare
      dnsNames:
        - "*.ggorockee.com"
        - "ggorockee.com"

clusterIssuer:
  name: letsencrypt-cloudflare
  email: ggorockee@gmail.com
  privateKeySecretName: letsencrypt-cloudflare-account-key
  credentials: cloudflare-webhook-credentials
  solvers:
    dnsNames:
      - "ggorockee.org"
      - "*.ggorockee.org"
      - "*.ggorockee.com"
      - "ggorockee.com"
