certmanager:
  certi:
    - name: ggorockee-com-cert
      namespace: cert-manager
      extraLabels: {}
      annotations: {}
      secretName: ggorockee-com-cert
      clusterIssuer:
        name: letsencrypt-cloudflare
      dnsNames:
        - "*.ggorockee.com"
        - "ggorockee.com"
      replicator:
        enabled: true
        targetNamespaces:
          - camping

    - name: ggorockee-org-cert
      namespace: cert-manager
      extraLabels: {}
      annotations: {}
      secretName: ggorockee-org-cert
      clusterIssuer:
        name: letsencrypt-cloudflare
      dnsNames:
        - "*.ggorockee.org"
        - "ggorockee.org"
      replicator:
        enabled: true
        targetNamespaces:
          - monitoring
          - argocd
          - kubeshark

    - name: woohalabs-com-cert
      namespace: cert-manager
      extraLabels: {}
      annotations: {}
      secretName: woohalabs-com-cert
      clusterIssuer:
        name: letsencrypt-cloudflare
      dnsNames:
        - "*.woohalabs.com"
      replicator:
        enabled: true
        targetNamespaces:
          - onedaypillo-dev
          - onedaypillo
          - fridge2fork
          - fridge2fork-dev

    - name: review-maps-com
      namespace: cert-manager
      extraLabels: {}
      annotations: {}
      secretName: review-maps-com
      clusterIssuer:
        name: letsencrypt-cloudflare
      dnsNames:
        - "*.review-maps.com"
        - "review-maps.com"
      replicator:
        enabled: true
        targetNamespaces:
          - reviewmaps

clusterIssuer:
  name: letsencrypt-cloudflare
  email: ggorockee@gmail.com
  privateKeySecretName: letsencrypt-cloudflare-account-key
  credentials: cloudflare-webhook-credentials
  solvers:
    dnsNames:
      - "ggorockee.org"
      - "*.ggorockee.org"
      - "*.ggorockee.com"
      - "ggorockee.com"
      - "savvyrev.com"
      - "*.savvyrev.com"
      - "*.review-maps.com"
      - "review-maps.com"
      - "*.fridge2fork.com"
      - "fridge2fork.com"
