certmanager:
  certi:
    - name: ggorockee-com-cert
      namespace: cert-manager
      extraLabels: {}
      annotations: {}
      secretName: ggorockee-com-cert
      clusterIssuer:
        name: letsencrypt-cloudflare
      dnsNames:
        - "*.ggorockee.com"
        - "ggorockee.com"
      replicator:
        enabled: true
        targetNamespaces:
          - camping

    - name: ggorockee-org-cert
      namespace: cert-manager
      extraLabels: {}
      annotations: {}
      secretName: ggorockee-org-cert
      clusterIssuer:
        name: letsencrypt-cloudflare
      dnsNames:
        - "*.ggorockee.org"
        - "ggorockee.org"
      replicator:
        enabled: true
        targetNamespaces:
          - monitoring
          - argocd
          - kubeshark

clusterIssuer:
  name: letsencrypt-cloudflare
  email: ggorockee@gmail.com
  privateKeySecretName: letsencrypt-cloudflare-account-key
  credentials: cloudflare-webhook-credentials
  solvers:
    dnsNames:
      - "ggorockee.org"
      - "*.ggorockee.org"
      - "*.ggorockee.com"
      - "ggorockee.com"
