# Default values for yangobot bot subchart
replicaCount: 2
revisionHistoryLimit: 1

image:
  repository: ggorockee/yangobot
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels:
  app: "yangobot"
  job: "yangobot"

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8080
  portName: "http"

resources:
  requests:
    cpu: 20m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /healthz
    port: http
    scheme: HTTP
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /healthz
    port: http
    scheme: HTTP
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

startupProbe:
  httpGet:
    path: /healthz
    port: http
    scheme: HTTP
  initialDelaySeconds: 0
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 12

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}

configMap:
  enabled: true
  name: ""
  data:
    REDIS_ADDR: "yangobot-redis-master:6379"

secret:
  enabled: true
  names:
    - yangobot-credentials
