backend:
  image:
    repository: ggorockee/py-webapp-backend
    tag: "20250704-f41a707"
  extraLabels:
    # 여기에 원하는 추가 레이블을 '키: 값' 형태로 정의
    app: camping
    service: camping-be
    component: webapp
  annotations:
    reloader.stakater.com/auto: "true"
  livenessProbe:
    enabled: true
    path: /healthz/ready # 1번 단계에서 추가한 헬스 체크 경로
    initialDelaySeconds: 30 # 파드가 시작되고 30초 후부터 검사 시작
    periodSeconds: 15 # 15초마다 검사
    timeoutSeconds: 5 # 응답 대기 시간 5초
    failureThreshold: 3 # 3번 연속 실패하면 재시작
  readinessProbe:
    enabled: true
    path: /healthz/ready # livenessProbe와 동일한 경로 사용 가능
    initialDelaySeconds: 10 # liveness보다 먼저, 더 짧게 검사 시작
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 2 # 2번 연속 실패 시 트래픽 차단
  service:
    port: 8000
  ingress:
    enabled: true
    className: "istio"
    annotations: {}
    hosts:
      - camping-api.ggorockee.com
    gateway:
      name: ""
  extraConfig:
    - name: django-config
      data:
        DEBUG: "off"
        DJANGO_ALLOWED_HOSTS: ".ggorockee.com,camping-umbrella-backend.camping.svc.cluster.local"
  extraSecrets: {}
frontend:
  image:
    repository: ggorockee/webapp-frontend-vue
    tag: "20250704-e5a7c11"
  extraLabels:
    app: camping
    service: camping-fe
    component: webapp
  annotations:
    reloader.stakater.com/auto: "true"
  livenessProbe:
    enabled: true
    path: /healthz/ready # 1번 단계에서 추가한 헬스 체크 경로
    initialDelaySeconds: 30 # 파드가 시작되고 30초 후부터 검사 시작
    periodSeconds: 15 # 15초마다 검사
    timeoutSeconds: 5 # 응답 대기 시간 5초
    failureThreshold: 3 # 3번 연속 실패하면 재시작
  readinessProbe:
    enabled: true
    path: /healthz/ready # livenessProbe와 동일한 경로 사용 가능
    initialDelaySeconds: 10 # liveness보다 먼저, 더 짧게 검사 시작
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 2 # 2번 연속 실패 시 트래픽 차단
  service:
    port: 80
  ingress:
    enabled: true
    className: "istio"
    annotations: {}
    hosts:
      - camping.ggorockee.com
    gateway:
      name: ""
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
  extraConfig:
    - name: process-env
      data:
        REACT_APP_DEBUG: "false"
  extraSecrets: {}
  # - name:
  #   data: {}
postgresql:
  global:
    postgresql:
      auth:
        username: ggorockee
        database: camping
        existingSecret: camping-db-credentials
  primary:
    annoations:
      reloader.stakater.com/auto: "true"
