daemonset:
  enabled: true
  secretMounts: []
  metricbeatConfig:
    metricbeat.yml: |
      metricbeat.modules:
      - module: kubernetes
        metricsets:
          - container
          - node
          - pod
          - system
          - volume
        period: 10s
        host: "${NODE_NAME}"
        hosts: ["https://${NODE_NAME}:10250"]
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        ssl.verification_mode: "none"
        processors:
        - add_kubernetes_metadata: ~

      - module: system
        period: 10s
        metricsets:
          - cpu
          - load
          - memory
          - network
          - process
          - process_summary
        processes: ['.*']
        process.include_top_n:
          by_cpu: 5
          by_memory: 5

      - module: system
        period: 1m
        metricsets:
          - filesystem
          - fsstat
        processors:
        - drop_event.when.regexp:
            system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'

      output.elasticsearch:
        hosts: ["http://elasticsearch-dev.logging.svc.cluster.local:9200"]
        ssl.enabled: false
        username: "elastic"
        password: "changeme"
        
deployment:
  enabled: true
  secretMounts: []
  metricbeatConfig:
    metricbeat.yml: |
      metricbeat.modules:
      - module: kubernetes
        enabled: true
        metricsets:
          - state_node
          - state_deployment
          - state_replicaset
          - state_pod
          - state_container
        period: 10s
        hosts: ["kube-state-metrics.logging.svc.cluster.local:8080"]

      output.elasticsearch:
        hosts: ["http://elasticsearch-dev.logging.svc.cluster.local:9200"]
        ssl.enabled: false
        username: "elastic"
        password: "changeme"

extraEnvs:
  - name: "ELASTICSEARCH_HOSTS"
    value: "elasticsearch-dev.logging.svc.cluster.local:9200"

kube_state_metrics:
  enabled: true
