database:
  enabled: true
  global:
    postgresql:
      auth:
        username: fridge2fork
        database: fridge2fork
        existingSecret: fridge2fork-db-credentials

  primary:
    persistence:
      size: 10Gi
      volumeName: "data"
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "500m"