# Scrape Service Configuration
scrape:
  enabled: true
  image:
    repository: ggorockee/fridge2fork-scrape
    tag: sha-8992dffe
    pullPolicy: IfNotPresent
  
  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080
  
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"
  
  replicas: 1
  
  # ServiceAccount configuration
  serviceAccount:
    create: true
    annotations: {}
    name: ""
  
  # Pod security context
  podSecurityContext:
    fsGroup: 2000
  
  # Container security context
  securityContext:
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
  
  # Pod annotations
  podAnnotations: {}
  
  # Image pull secrets
  imagePullSecrets: []
  
  # Node selector
  nodeSelector: {}
  
  # Tolerations
  tolerations: []
  
  # Affinity
  affinity: {}
  
  # Autoscaling
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
  
  # Environment variables from secrets
  envFrom:
    - secretRef:
        name: fridge2fork-db-credentials

# Database Configuration
database:
  enabled: true
  global:
    postgresql:
      auth:
        username: refridge2fork
        database: refridge2fork
        existingSecret: fridge2fork-db-credentials

  primary:
    persistence:
      size: 10Gi
      volumeName: "data"
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "500m"