apiVersion: v2
appVersion: "1.0"
description: Server subchart for Fridge2Fork application
home: https://github.com/ggorockee/fridge2fork
keywords:
- server
- fridge2fork
maintainers:
- email: ggorockee@example.com
  name: ggorockee
name: server
sources:
- https://github.com/ggorockee/fridge2fork
type: application
version: 0.1.0
