# Server Service Configuration
replicaCount: 1

# Image configuration
image:
  repository: ggorockee/fridge2fork-dev-server
  tag: dev
  pullPolicy: IfNotPresent

# Service configuration
service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

# Resource limits and requests
resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "200m"

# ServiceAccount configuration
serviceAccount:
  create: true
  annotations: {}
  name: ""
  automount: true

# ConfigMap configuration
configMap:
  enabled: true
  config:
    MAIN_PORT: "8000"
    LOG_LEVEL: "INFO"
    DEBUG_MODE: "false"

# Secret configuration
secret:
  enabled: true
  secretName: "fridge2fork-db-credentials"

# Pod security context
podSecurityContext:
  fsGroup: 2000

# Container security context
securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

# Pod annotations
podAnnotations: {}

# Image pull secrets
imagePullSecrets: []

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}

# HPA (Horizontal Pod Autoscaler) configuration
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Health check configuration
healthCheck:
  enabled: false
  livenessProbe:
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /ready
      port: http
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3

# Init container for Django migrations
initContainer:
  enabled: true
  name: migrate
  command: ["/bin/bash", "-c"]
  args:
    - |
      set -e
      echo "🔧 Running database migrations..."
      cd /app/app
      /usr/local/bin/uv run python manage.py makemigrations --noinput || true
      /usr/local/bin/uv run python manage.py migrate --noinput
      echo "✅ Migrations completed successfully"
  env:
    - name: PATH
      value: "/root/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    - name: ENVIRONMENT
      value: "development"
    - name: RUN_MIGRATIONS
      value: "true"
    - name: AUTO_MIGRATE
      value: "false"
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "100m"

# Environment variables from external sources
envFrom: []
