# Main Application Configuration
serviceAccount:
  create: true
  annotations: {}
  name: ""
  automount: true

# Scrape Service Configuration (Disabled - not used for scraping)
scrape:
  enabled: false
<<<<<<< HEAD
  replicaCount: 1

=======
>>>>>>> main
  image:
    repository: ggorockee/fridge2fork-dev-scrape
    tag: sha-b13755d7
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 8000
    targetPort: 8000
    portName: "fastapi"

  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"

  # ServiceAccount configuration
  serviceAccount:
    create: true
    annotations: {}
    name: ""
    automount: true

  # Pod security context
  podSecurityContext:
    fsGroup: 2000

  # Container security context
  securityContext:
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000

  # Pod annotations
  podAnnotations: {}

  # Image pull secrets
  imagePullSecrets: []

  # Node selector
  nodeSelector: {}

  # Tolerations
  tolerations: []

  # Affinity
  affinity: {}

  # Autoscaling
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  # Health check configuration
  healthCheck:
    enabled: true
    livenessProbe:
      httpGet:
        path: /fridge2fork/v1/system/health
        port: http
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /fridge2fork/v1/system/health
        port: http
      initialDelaySeconds: 10
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 3

  # Secret configuration
  # REQUIRED: This secret must exist before deploying the chart
  secret:
    enabled: true
    secretName: "fridge2fork-db-credentials"

  # ConfigMap configuration
  configMap:
    enabled: true
    config:
      # Python 설정
      PYTHONPATH: "/app"
      PYTHONUNBUFFERED: "1"

      # 애플리케이션 설정
      APP_NAME: "fridge2fork"
      APP_VERSION: "1.0.0"
      APP_ENV: "development"
      LOG_LEVEL: "INFO"

  # Init container for Alembic migration
  initContainer:
    enabled: true
    resources:
      requests:
        memory: "128Mi"
        cpu: "50m"
      limits:
        memory: "256Mi"
        cpu: "100m"
# Backend Service Configuration
server:
  enabled: true
  replicaCount: 1

  image:
    repository: ggorockee/fridge2fork-dev-server
    tag: sha-b13755d7
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 8000
    targetPort: 8000
    portName: "fastapi"

  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"

  serviceAccount:
    create: true
    annotations: {}
    name: ""
    automount: true

  configMap:
    enabled: true
    config:
      MAIN_PORT: "8000"
      LOG_LEVEL: "INFO"
      DEBUG_MODE: "false"

  secret:
    enabled: true
    secretName: "fridge2fork-db-credentials"

  podSecurityContext:
    fsGroup: 2000

  securityContext:
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000

  podAnnotations: {}
  imagePullSecrets: []
  nodeSelector: {}
  tolerations: []
  affinity: {}

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  healthCheck:
    enabled: false
    livenessProbe:
      httpGet:
        path: /health
        port: http
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /ready
        port: http
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 3

  envFrom: []



# Database Configuration
database:
  enabled: true
  global:
    postgresql:
      auth:
        username: fridge2fork
        database: fridge2fork
        existingSecret: fridge2fork-db-credentials

  primary:
    persistence:
      size: 10Gi
      volumeName: "data"
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "500m"


