# Main Application Configuration
serviceAccount:
  create: true
  annotations: {}
  name: ""
  automount: true

# Backend Service Configuration
server:
  enabled: true
  replicaCount: 1

  image:
    repository: ggorockee/fridge2fork-dev-server
    tag: sha-bd388ddc
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 8000
    targetPort: 8000
    portName: "fastapi"

  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"

  serviceAccount:
    create: true
    annotations: {}
    name: ""
    automount: true

  configMap:
    enabled: true
    config:
      MAIN_PORT: "8000"
      LOG_LEVEL: "INFO"
      DEBUG_MODE: "false"
      PYTHONPATH: "/app"
      PYTHONUNBUFFERED: "1"
      APP_NAME: "fridge2fork"
      APP_VERSION: "1.0.0"
      APP_ENV: "development"

  secret:
    enabled: true
    secretName: "fridge2fork-db-credentials"

  podSecurityContext:
    fsGroup: 2000

  securityContext:
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000

  podAnnotations: {}
  imagePullSecrets: []
  nodeSelector: {}
  tolerations: []
  affinity: {}

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  healthCheck:
    enabled: true
    livenessProbe:
      httpGet:
        path: /fridge2fork/v1/system/health
        port: http
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /fridge2fork/v1/system/health
        port: http
      initialDelaySeconds: 10
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 3

  # Init container for Alembic migration
  initContainer:
    enabled: true
    resources:
      requests:
        memory: "128Mi"
        cpu: "50m"
      limits:
        memory: "256Mi"
        cpu: "100m"
