extraConfigmap:
  enabled: true
  config:
    - name: nginx-access-logging
      namespace: camping
      extraLabels:
        {}
        # project: my-project
        # team: backend
      annotations:
        {}
        # description: "This configmap has extra labels and annotations"
        # owner: "John Doe"
      data:
        access.conf: |-
          # JSON 로그 포맷
          log_format json_analytics escape=json '{'
              '"msec":"$msec",'
              '"connection":"$connection",'
              '"connection_requests":"$connection_requests",'
              '"pid":"$pid",'
              '"request_id":"$request_id",'
              '"request_length":"$request_length",'
              '"remote_addr":"$remote_addr",'
              '"remote_user":"$remote_user",'
              '"remote_port":"$remote_port",'
              '"time_local":"$time_local",'
              '"time_iso8601":"$time_iso8601",'
              '"request":"$request",'
              '"request_uri":"$request_uri",'
              '"args":"$args",'
              '"status":"$status",'
              '"body_bytes_sent":"$body_bytes_sent",'
              '"bytes_sent":"$bytes_sent",'
              '"http_referer":"$http_referer",'
              '"http_user_agent":"$http_user_agent",'
              '"http_x_forwarded_for":"$http_x_forwarded_for",'
              '"http_host":"$http_host",'
              '"server_name":"$server_name",'
              '"request_time":"$request_time",'
              '"upstream":"$upstream_addr",'
              '"upstream_connect_time":"$upstream_connect_time",'
              '"upstream_header_time":"$upstream_header_time",'
              '"upstream_response_time":"$upstream_response_time",'
              '"upstream_response_length":"$upstream_response_length",'
              '"upstream_cache_status":"$upstream_cache_status",'
              '"ssl_protocol":"$ssl_protocol",'
              '"ssl_cipher":"$ssl_cipher",'
              '"scheme":"$scheme",'
              '"request_method":"$request_method",'
              '"server_protocol":"$server_protocol",'
              '"pipe":"$pipe",'
              '"gzip_ratio":"$gzip_ratio",'
              '"http_cf_ray":"$http_cf_ray"'
            '}';
          # 로그를 파일로 남기기
          access_log /var/log/nginx/json_access.log json_analytics;
          access_log /dev/stdout          json_analytics;

extraSecret:
  enabled: true
  secrets:
    - name: camping-umbrella-front-cloudflare
      namespace: camping
      extraLabels:
        {}
        # project: my-project
        # team: backend
      annotations:
        {}
        # description: "This configmap has extra labels and annotations"
        # owner: "John Doe"
      encryptedData:
        VITE_CLOUDFLARE_ACCOUNT_HASH: AgBR4+f44uTKXChshJwk9BnKtv1vf9Vy9K9HX3X2+CvN8vVwrnvLU7zwnstFHgX+dEa0h/yEidjPjyVIKT9MFEJ8eEjlBP89ETnnFTZo/wiCdJ/BeYRw8yiVhYUMdmklIHwyXo+o0U4yJ6/S6f9olq23714TSpYC2vEtu3Kwm66Dxuc2GiZsCYqDkj3goB4jSERIdjVdGRWKzpHMhASAr0UUytQ6VeYKO79iQK1K8ERb7Rqt50iGu5idrc16pjS4nH8rLGl3ROCYvbYrxUnU81I56yalsrUEC7E8MANHZpzbMrb/4t5/mF27oBw6vg1sgXE13EsD2qumcMjLK94IUBHWv80vk8ZEpEOXvzAmGhWWaImahzScJuy1s1eeY3PUogfqOc6FKjAIkNUypxv/LqCSlUMplkb0SN/IdjTzhdOUGNT1p0AWzmmPBrDTwcrbZIxG7gK8OXdolVpuaJJgxFxg6HerTslbZ6YpCevvNZsdDOZQivo25l1tssRuyvgVMp7L/5rD8tIZAGAOgJfLQWpt10s54HQwl3rL2F0wF3t5bxR3bfiQYbnkeZVPVQiOz8JqVDyyzz1W4O4ue0BAIwbfVTwKx5/cat2ISSvHGlRcTqDdIa7KYajekSzGvznKFrcUxVxDtF1vWnEaUrDFjoEMn3/HJSAypjHc1/hKa54oy1sbe8AM7sqB1N+HmXI98D7G/hK3hYfCk/wBo+eHqEPWaiDl2ew8
