global:
  httpToHttpsRedirect:
    enabled: true # ← 이 값만 켜면 모든 HTTP 요청을 HTTPS로 리다이렉트

# values.yaml
ingressRoutes:
  # 첫 번째 라우팅 규칙: ArgoCD
  - name: argocd
    enabled: true
    namespace: argocd

    # 라우팅 진입점 (보통 websecure는 443/HTTPS를 의미)
    entryPoints:
      - websecure

    # 2. Host 설정하는 부분
    host: "argocd.ggorockee.org"

    # 1. secretName 설정하는 부분
    tlsSecretName: "ggorockee-org-cert"

    # 3. Services 설정하는 부분 (여기도 리스트 형태)
    services:
      - name: argocd-server
        port: 80

  - name: camping-umbrella-frontend
    enabled: true
    namespace: camping

    entryPoints:
      - websecure

    host: "camping.ggorockee.com"
    tlsSecretName: "ggorockee-com-cert"

    services:
      - name: camping-umbrella-frontend
        port: 80

    # --- 리다이렉트 기능 활성화 ---
    redirect:
      enabled: false
      # 리다이렉트 될 최종 목적지 주소
      targetURL: "https://ggorockee.com"

  - name: camping-umbrella-backend
    enabled: true
    namespace: camping

    entryPoints:
      - websecure

    host: "camping-api.ggorockee.com"
    tlsSecretName: "ggorockee-com-cert"

    services:
      - name: camping-umbrella-backend
        port: 8000

  - name: grafana
    enabled: true
    namespace: monitoring

    entryPoints:
      - websecure

    host: "grafana.ggorockee.org"
    tlsSecretName: "ggorockee-org-cert"

    services:
      - name: kube-prometheus-stack-grafana
        port: 80

  - name: prometheus
    enabled: true
    namespace: monitoring

    entryPoints:
      - websecure

    host: "prom.ggorockee.org"
    tlsSecretName: "ggorockee-org-cert"

    services:
      - name: kube-prometheus-stack-prometheus
        port: 9090
