apiVersion: v1
kind: Service
metadata:
  name: {{ include "scrape.fullname" . }}
  labels:
    {{- include "scrape.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-15"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "scrape.selectorLabels" . | nindent 4 }}
